# exporters:
#   azureMonitor:
#     instrumentationKey: "111a0d2f-ab53-4b62-a54f-4722f09fd136"

exporters:
  jaeger:
    service_name: "opencensus"
    collector_endpoint: "http://localhost:14268/api/traces"
